services:
  events-db:
    image: mysql:latest
    container_name: events-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=events_password
      - MYSQL_USER=events_user
      - MYSQL_DATABASE=events_db
      - MYSQL_PASSWORD=events_password
    ports:
      - "3306:3306"
    volumes:
      - events_data:/var/lib/mysql

  venue-db:
    image: mysql:latest
    container_name: venue-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=venue_password
      - MYSQL_USER=venue_user
      - MYSQL_DATABASE=venue_db
      - MYSQL_PASSWORD=venue_password
    ports:
      - "3307:3306"
    volumes:
      - venue_data:/var/lib/mysql

  user-db:
    image: mysql:latest
    container_name: user-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=user_password
      - MYSQL_USER=user_user
      - MYSQL_DATABASE=user_db
      - MYSQL_PASSWORD=user_password
    ports:
      - "3308:3306"
    volumes:
      - user_data:/var/lib/mysql

volumes:
    events_data:
    venue_data:
    user_data: